/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package generatoretags.gui.panels.project;

import generatoretags.commons.events.CloseRequestListener;
import generatoretags.data.Project;
import generatoretags.gui.SharedData;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author gabri
 */
public class ProjectCreator extends javax.swing.JPanel {

    private final SharedData sharedData;
    private CloseRequestListener listener;

    /**
     * Creates new form ProjectCreator
     *
     * @param sharedData
     */
    public ProjectCreator(SharedData sharedData) {
        initComponents();
        this.sharedData = sharedData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Title = new javax.swing.JLabel();
        NewProjectPanel = new javax.swing.JPanel();
        NewLabel = new javax.swing.JLabel();
        ProjectNameTF = new javax.swing.JTextField();
        GenerateProject = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Title1 = new javax.swing.JLabel();
        NewProjectPanel1 = new javax.swing.JPanel();
        OpenLabel = new javax.swing.JLabel();
        ProjectPathTF = new javax.swing.JTextField();
        OpenProject = new javax.swing.JButton();
        ShowExplorer = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(330, 209));
        setMinimumSize(new java.awt.Dimension(330, 209));
        setLayout(new java.awt.GridBagLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Nuovo Progetto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(Title, gridBagConstraints);

        NewLabel.setText("Nome:");

        GenerateProject.setText("Genera");
        GenerateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewProjectPanelLayout = new javax.swing.GroupLayout(NewProjectPanel);
        NewProjectPanel.setLayout(NewProjectPanelLayout);
        NewProjectPanelLayout.setHorizontalGroup(
            NewProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewProjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewProjectPanelLayout.createSequentialGroup()
                        .addComponent(NewLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NewProjectPanelLayout.createSequentialGroup()
                        .addComponent(ProjectNameTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenerateProject)))
                .addContainerGap())
        );
        NewProjectPanelLayout.setVerticalGroup(
            NewProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewProjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenerateProject))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(NewProjectPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 323;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(jSeparator1, gridBagConstraints);

        Title1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("Apri Progetto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(Title1, gridBagConstraints);

        OpenLabel.setText("Percorso Progetto:");

        OpenProject.setText("Apri");
        OpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenProjectActionPerformed(evt);
            }
        });

        ShowExplorer.setText("...");
        ShowExplorer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowExplorerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewProjectPanel1Layout = new javax.swing.GroupLayout(NewProjectPanel1);
        NewProjectPanel1.setLayout(NewProjectPanel1Layout);
        NewProjectPanel1Layout.setHorizontalGroup(
            NewProjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewProjectPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewProjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewProjectPanel1Layout.createSequentialGroup()
                        .addComponent(OpenLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NewProjectPanel1Layout.createSequentialGroup()
                        .addComponent(ProjectPathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ShowExplorer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OpenProject)))
                .addContainerGap())
        );
        NewProjectPanel1Layout.setVerticalGroup(
            NewProjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewProjectPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OpenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewProjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectPathTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowExplorer)
                    .addComponent(OpenProject))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(NewProjectPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateProjectActionPerformed
        // TODO add your handling code here:
        String text = ProjectNameTF.getText();
        if ("".equals(text.trim())) {
            return;
        }
        Project p = new Project(text);
        sharedData.setOpenedProject(p);
        if (this.listener != null) {
            listener.onCloseRequest();
        }
    }//GEN-LAST:event_GenerateProjectActionPerformed

    private void OpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenProjectActionPerformed
        // TODO add your handling code here:
        String text = ProjectPathTF.getText();
        if ("".equals(text.trim())) {
            return;
        }
        if (this.listener != null) {
            listener.onCloseRequest();
        }
    }//GEN-LAST:event_OpenProjectActionPerformed

    private void ShowExplorerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowExplorerActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.setAcceptAllFileFilterUsed(true);
        FileFilter ff = new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().endsWith(".gtpj");
            }

            @Override
            public String getDescription() {
                return "GTPJ - File di Progetto";
            }
        };
        jfc.setFileFilter(ff);
        jfc.showOpenDialog(this);
        File selectedFile = jfc.getSelectedFile();
        if (selectedFile != null) {
            ProjectPathTF.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_ShowExplorerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateProject;
    private javax.swing.JLabel NewLabel;
    private javax.swing.JPanel NewProjectPanel;
    private javax.swing.JPanel NewProjectPanel1;
    private javax.swing.JLabel OpenLabel;
    private javax.swing.JButton OpenProject;
    private javax.swing.JTextField ProjectNameTF;
    private javax.swing.JTextField ProjectPathTF;
    private javax.swing.JButton ShowExplorer;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void addCloseRequestListener(CloseRequestListener crl) {
        listener = crl;
    }

}
