/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package generatoretags.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import generatoretags.gui.frames.ProjectDefinitions;
import generatoretags.gui.panels.project.ProjectCreator;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;

/**
 *
 * @author gabri
 */
public class MainApp extends javax.swing.JFrame {

    private static final SharedData sharedData = new SharedData();

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        var v = new ProjectDefinitions();
        v.setLocation(50, 50);
        v.setVisible(true);
        DesktopPane.add(v);
        initDataListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        AppMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        NewProject = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(755, 441));
        setSize(new java.awt.Dimension(755, 441));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        DesktopPane.setAutoscrolls(true);
        DesktopPane.setMinimumSize(new java.awt.Dimension(755, 418));
        getContentPane().add(DesktopPane);

        FileMenu.setText("File");

        NewProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        NewProject.setText("Nuovo Progetto");
        NewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProjectActionPerformed(evt);
            }
        });
        FileMenu.add(NewProject);

        AppMenuBar.add(FileMenu);

        EditMenu.setText("Edit");
        AppMenuBar.add(EditMenu);

        setJMenuBar(AppMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProjectActionPerformed
        // TODO add your handling code here:
        ProjectCreator content = new ProjectCreator(sharedData);

        JInternalFrame jif = new JInternalFrame("Nuovo progetto", false, true, true, true);
        jif.setLayout(new GridBagLayout());
        jif.add(content);
        Dimension preferredSize = content.getMinimumSize();
        preferredSize.height = preferredSize.height + 20;
        preferredSize.width = preferredSize.width + 20;
        jif.setSize(preferredSize);
        jif.setVisible(true);
        //JInternalFrame jif = FrameCreator.createFrame("Nuovo progetto", false, content);
        jif.setLayer(3);
        this.DesktopPane.add(jif);

        content.addCloseRequestListener(() -> {
            jif.setVisible(false);
            this.DesktopPane.remove(jif);
        });
    }//GEN-LAST:event_NewProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println(ex.toString());
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainApp app = new MainApp();
            app.setIconImage(new ImageIcon(MainApp.class.getResource("/generatoretags/resources/icon.png")).getImage());
            app.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar AppMenuBar;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem NewProject;
    // End of variables declaration//GEN-END:variables

    private void initDataListeners() {
        sharedData.addProjectEventListener((data) -> {
            this.setTitle(data.getProjectName());
        });
    }

}
